
package sessionbeans;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FileServiceService", targetNamespace = "http://sessionBeans/", wsdlLocation = "http://localhost:8080/DocMan/FileService?wsdl")
public class FileServiceService
    extends Service
{

    private final static URL FILESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sessionbeans.FileServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sessionbeans.FileServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/DocMan/FileService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/DocMan/FileService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FILESERVICESERVICE_WSDL_LOCATION = url;
    }

    public FileServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileServiceService() {
        super(FILESERVICESERVICE_WSDL_LOCATION, new QName("http://sessionBeans/", "FileServiceService"));
    }

    /**
     * 
     * @return
     *     returns FileServiceRemote
     */
    @WebEndpoint(name = "FileServicePort")
    public FileServiceRemote getFileServicePort() {
        return super.getPort(new QName("http://sessionBeans/", "FileServicePort"), FileServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileServiceRemote
     */
    @WebEndpoint(name = "FileServicePort")
    public FileServiceRemote getFileServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sessionBeans/", "FileServicePort"), FileServiceRemote.class, features);
    }

}
