
package useraccount.soap.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://services.soap.useraccount/", wsdlLocation = "http://localhost:8080/userGate/Hello?wsdl")
public class HelloService_Service
    extends Service
{

    private final static URL HELLOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(useraccount.soap.services.HelloService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = useraccount.soap.services.HelloService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/userGate/Hello?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/userGate/Hello?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOSERVICE_WSDL_LOCATION = url;
    }

    public HelloService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService_Service() {
        super(HELLOSERVICE_WSDL_LOCATION, new QName("http://services.soap.useraccount/", "HelloService"));
    }

    /**
     * 
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloPort")
    public HelloService getHelloPort() {
        return super.getPort(new QName("http://services.soap.useraccount/", "HelloPort"), HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloPort")
    public HelloService getHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.soap.useraccount/", "HelloPort"), HelloService.class, features);
    }

}
