
package useraccount.soap.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccountService", targetNamespace = "http://services.soap.useraccount/", wsdlLocation = "http://localhost:8080/userGate/AccountService?wsdl")
public class AccountService
    extends Service
{

    private final static URL ACCOUNTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(useraccount.soap.services.AccountService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = useraccount.soap.services.AccountService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/userGate/AccountService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/userGate/AccountService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCOUNTSERVICE_WSDL_LOCATION = url;
    }

    public AccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountService() {
        super(ACCOUNTSERVICE_WSDL_LOCATION, new QName("http://services.soap.useraccount/", "AccountService"));
    }

    /**
     * 
     * @return
     *     returns PersonInterface
     */
    @WebEndpoint(name = "AccountServicePort")
    public PersonInterface getAccountServicePort() {
        return super.getPort(new QName("http://services.soap.useraccount/", "AccountServicePort"), PersonInterface.class);
    }

    /**
     * 
     * @param features
     *     A labourList of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonInterface
     */
    @WebEndpoint(name = "AccountServicePort")
    public PersonInterface getAccountServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.soap.useraccount/", "AccountServicePort"), PersonInterface.class, features);
    }

}
