
package usergate.classes;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "personInterface", targetNamespace = "http://classes.userGate/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonInterface {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserToGroup", targetNamespace = "http://classes.userGate/", className = "usergate.classes.AddUserToGroup")
    @ResponseWrapper(localName = "addUserToGroupResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.AddUserToGroupResponse")
    public String addUserToGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://classes.userGate/", className = "usergate.classes.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignRole", targetNamespace = "http://classes.userGate/", className = "usergate.classes.AssignRole")
    @ResponseWrapper(localName = "assignRoleResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.AssignRoleResponse")
    public void assignRole(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<usergate.classes.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSomeone", targetNamespace = "http://classes.userGate/", className = "usergate.classes.FindSomeone")
    @ResponseWrapper(localName = "findSomeoneResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.FindSomeoneResponse")
    public List<Person> findSomeone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<usergate.classes.UserRoles>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRoles", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetRoles")
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetRolesResponse")
    public List<UserRoles> getRoles();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRoleByName", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetRoleByName")
    @ResponseWrapper(localName = "getRoleByNameResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetRoleByNameResponse")
    public String getRoleByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupDNfrom", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetGroupDNfrom")
    @ResponseWrapper(localName = "getGroupDNfromResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetGroupDNfromResponse")
    public String getGroupDNfrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrgs", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetOrgs")
    @ResponseWrapper(localName = "getOrgsResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetOrgsResponse")
    public List<Object> getOrgs();

    /**
     * 
     * @return
     *     returns java.util.List<usergate.classes.Groups>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userGroup", targetNamespace = "http://classes.userGate/", className = "usergate.classes.UserGroup")
    @ResponseWrapper(localName = "userGroupResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.UserGroupResponse")
    public List<Groups> userGroup();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://classes.userGate/", className = "usergate.classes.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.LoginResponse")
    public boolean login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeRole", targetNamespace = "http://classes.userGate/", className = "usergate.classes.RemoveRole")
    @ResponseWrapper(localName = "removeRoleResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.RemoveRoleResponse")
    public void removeRole(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserAttribute", targetNamespace = "http://classes.userGate/", className = "usergate.classes.AddUserAttribute")
    @ResponseWrapper(localName = "addUserAttributeResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.AddUserAttributeResponse")
    public boolean addUserAttribute(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "migrateUser", targetNamespace = "http://classes.userGate/", className = "usergate.classes.MigrateUser")
    @ResponseWrapper(localName = "migrateUserResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.MigrateUserResponse")
    public void migrateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns usergate.classes.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userProfile", targetNamespace = "http://classes.userGate/", className = "usergate.classes.UserProfile")
    @ResponseWrapper(localName = "userProfileResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.UserProfileResponse")
    public Person userProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://classes.userGate/", className = "usergate.classes.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.CreatePersonResponse")
    public void createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRole", targetNamespace = "http://classes.userGate/", className = "usergate.classes.FindRole")
    @ResponseWrapper(localName = "findRoleResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.FindRoleResponse")
    public String findRole();

    /**
     * 
     * @return
     *     returns java.util.List<usergate.classes.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetPersonsResponse")
    public List<Person> getPersons();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<usergate.classes.UserRoles>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "personRoles", targetNamespace = "http://classes.userGate/", className = "usergate.classes.PersonRoles")
    @ResponseWrapper(localName = "personRolesResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.PersonRolesResponse")
    public List<UserRoles> personRoles(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns usergate.classes.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByUsername", targetNamespace = "http://classes.userGate/", className = "usergate.classes.FindByUsername")
    @ResponseWrapper(localName = "findByUsernameResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.FindByUsernameResponse")
    public Person findByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrgUnit", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetOrgUnit")
    @ResponseWrapper(localName = "getOrgUnitResponse", targetNamespace = "http://classes.userGate/", className = "usergate.classes.GetOrgUnitResponse")
    public List<Object> getOrgUnit();

}
