
package usergate.classes;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "personImplService", targetNamespace = "http://classes.userGate/", wsdlLocation = "http://localhost:8080/userGate/personImpl?wsdl")
public class PersonImplService
    extends Service
{

    private final static URL PERSONIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(usergate.classes.PersonImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = usergate.classes.PersonImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/userGate/personImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/userGate/personImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PERSONIMPLSERVICE_WSDL_LOCATION = url;
    }

    public PersonImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonImplService() {
        super(PERSONIMPLSERVICE_WSDL_LOCATION, new QName("http://classes.userGate/", "personImplService"));
    }

    /**
     * 
     * @return
     *     returns PersonInterface
     */
    @WebEndpoint(name = "personImplPort")
    public PersonInterface getPersonImplPort() {
        return super.getPort(new QName("http://classes.userGate/", "personImplPort"), PersonInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonInterface
     */
    @WebEndpoint(name = "personImplPort")
    public PersonInterface getPersonImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://classes.userGate/", "personImplPort"), PersonInterface.class, features);
    }

}
