
package docman.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileService", targetNamespace = "http://services.docman/", wsdlLocation = "http://localhost:8080/DocMan/FileService/FileService?wsdl")
public class FileService
    extends Service
{

    private final static URL FILESERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESERVICE_EXCEPTION;
    private final static QName FILESERVICE_QNAME = new QName("http://services.docman/", "FileService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DocMan/FileService/FileService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESERVICE_WSDL_LOCATION = url;
        FILESERVICE_EXCEPTION = e;
    }

    public FileService() {
        super(__getWsdlLocation(), FILESERVICE_QNAME);
    }

    public FileService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESERVICE_QNAME, features);
    }

    public FileService(URL wsdlLocation) {
        super(wsdlLocation, FILESERVICE_QNAME);
    }

    public FileService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESERVICE_QNAME, features);
    }

    public FileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileServiceRemote
     */
    @WebEndpoint(name = "SOAPFileService")
    public FileServiceRemote getSOAPFileService() {
        return super.getPort(new QName("http://services.docman/", "SOAPFileService"), FileServiceRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileServiceRemote
     */
    @WebEndpoint(name = "SOAPFileService")
    public FileServiceRemote getSOAPFileService(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.docman/", "SOAPFileService"), FileServiceRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESERVICE_EXCEPTION!= null) {
            throw FILESERVICE_EXCEPTION;
        }
        return FILESERVICE_WSDL_LOCATION;
    }

}
