
package webframeapp.servicelgoic;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EntityService", targetNamespace = "http://serviceLgoic.webFrameApp/", wsdlLocation = "http://localhost:8080/RDwebFrameApp/EntityService?wsdl")
public class EntityService
    extends Service
{

    private final static URL ENTITYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webframeapp.servicelgoic.EntityService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webframeapp.servicelgoic.EntityService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RDwebFrameApp/EntityService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RDwebFrameApp/EntityService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ENTITYSERVICE_WSDL_LOCATION = url;
    }

    public EntityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntityService() {
        super(ENTITYSERVICE_WSDL_LOCATION, new QName("http://serviceLgoic.webFrameApp/", "EntityService"));
    }

    /**
     * 
     * @return
     *     returns IEntityService
     */
    @WebEndpoint(name = "SOAPOverHTTP")
    public IEntityService getSOAPOverHTTP() {
        return super.getPort(new QName("http://serviceLgoic.webFrameApp/", "SOAPOverHTTP"), IEntityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEntityService
     */
    @WebEndpoint(name = "SOAPOverHTTP")
    public IEntityService getSOAPOverHTTP(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceLgoic.webFrameApp/", "SOAPOverHTTP"), IEntityService.class, features);
    }

}
