
package webframeapp.servicelgoic;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import webframeapp.interfaces.FeedPost;
import webframeapp.interfaces.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FeedPostDAO", targetNamespace = "http://interfaces.webFrameApp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FeedPostDAO {


    /**
     * 
     * @return
     *     returns java.util.List<webframeapp.interfaces.FeedPost>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPosts", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.ListPosts")
    @ResponseWrapper(localName = "listPostsResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.ListPostsResponse")
    public List<FeedPost> listPosts();

    /**
     * 
     * @param arg0
     * @return
     *     returns webframeapp.interfaces.FeedPost
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.FindByIdResponse")
    public FeedPost findById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.SayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createPost", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.CreatePost")
    @ResponseWrapper(localName = "createPostResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.CreatePostResponse")
    public void createPost(
        @WebParam(name = "arg0", targetNamespace = "")
        FeedPost arg0);

}
