
package webframeapp.servicelgoic;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import webframeapp.interfaces.Domain;
import webframeapp.interfaces.ObjectFactory;
import webframeapp.interfaces.OrgEntity;
import webframeapp.interfaces.SqldataTypes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IEntityService", targetNamespace = "http://interfaces.webFrameApp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEntityService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.DeleteResponse")
    public boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        OrgEntity arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webframeapp.interfaces.OrgEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByDomain", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.FindByDomain")
    @ResponseWrapper(localName = "findByDomainResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.FindByDomainResponse")
    public List<OrgEntity> findByDomain(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "relateEntities", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.RelateEntities")
    @ResponseWrapper(localName = "relateEntitiesResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.RelateEntitiesResponse")
    public void relateEntities(
        @WebParam(name = "arg0", targetNamespace = "")
        OrgEntity arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        OrgEntity arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     */
    @WebMethod(operationName = "CreateEntity")
    @RequestWrapper(localName = "CreateEntity", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.CreateEntity")
    @ResponseWrapper(localName = "CreateEntityResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.CreateEntityResponse")
    public void createEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        Domain arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<String> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        List<String> arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        List<SqldataTypes> arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        List<Integer> arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        List<String> arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        List<String> arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newRelationship", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.NewRelationship")
    @ResponseWrapper(localName = "newRelationshipResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.NewRelationshipResponse")
    public boolean newRelationship(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webframeapp.interfaces.OrgEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByName", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.FindByNameResponse")
    public List<OrgEntity> findByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webframeapp.interfaces.OrgEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://interfaces.webFrameApp/", className = "webframeapp.interfaces.FindAllResponse")
    public List<OrgEntity> findAll();

}
