
package birthcertificate.ews.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BEServiceService", targetNamespace = "http://soap.ews.birthcertificate/", wsdlLocation = "http://localhost:8080/BCManager/services/bcs?wsdl")
public class BEServiceService
    extends Service
{

    private final static URL BESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BESERVICESERVICE_EXCEPTION;
    private final static QName BESERVICESERVICE_QNAME = new QName("http://soap.ews.birthcertificate/", "BEServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BCManager/services/bcs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BESERVICESERVICE_WSDL_LOCATION = url;
        BESERVICESERVICE_EXCEPTION = e;
    }

    public BEServiceService() {
        super(__getWsdlLocation(), BESERVICESERVICE_QNAME);
    }

    public BEServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BESERVICESERVICE_QNAME, features);
    }

    public BEServiceService(URL wsdlLocation) {
        super(wsdlLocation, BESERVICESERVICE_QNAME);
    }

    public BEServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BESERVICESERVICE_QNAME, features);
    }

    public BEServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BEServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBEService
     */
    @WebEndpoint(name = "ibcservice")
    public IBEService getIbcservice() {
        return super.getPort(new QName("http://soap.ews.birthcertificate/", "ibcservice"), IBEService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBEService
     */
    @WebEndpoint(name = "ibcservice")
    public IBEService getIbcservice(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ews.birthcertificate/", "ibcservice"), IBEService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BESERVICESERVICE_EXCEPTION!= null) {
            throw BESERVICESERVICE_EXCEPTION;
        }
        return BESERVICESERVICE_WSDL_LOCATION;
    }

}
