
package birthcertificate.ews.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBEService", targetNamespace = "http://soap.ews.birthcertificate/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBEService {


    /**
     * 
     * @return
     *     returns java.util.List<birthcertificate.ews.soap.CollectionStatus>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "applications", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.Applications")
    @ResponseWrapper(localName = "applicationsResponse", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.ApplicationsResponse")
    public List<CollectionStatus> applications();

    /**
     * 
     * @return
     *     returns java.util.List<birthcertificate.ews.soap.BCertificate>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "approved", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.Approved")
    @ResponseWrapper(localName = "approvedResponse", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.ApprovedResponse")
    public List<BCertificate> approved();

    /**
     * 
     * @param parentId
     * @return
     *     returns birthcertificate.ews.soap.CollectionStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkStatus", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.CheckStatus")
    @ResponseWrapper(localName = "checkStatusResponse", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.CheckStatusResponse")
    public CollectionStatus checkStatus(
        @WebParam(name = "parentId", targetNamespace = "")
        int parentId);

    /**
     * 
     * @param arg0
     * @return
     *     returns birthcertificate.ews.soap.SystemMessage
     */
    @WebMethod(operationName = "BatchApplication")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BatchApplication", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.BatchApplication")
    @ResponseWrapper(localName = "BatchApplicationResponse", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.BatchApplicationResponse")
    public SystemMessage batchApplication(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param labour
     * @return
     *     returns birthcertificate.ews.soap.SystemMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createApplication", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.CreateApplication")
    @ResponseWrapper(localName = "createApplicationResponse", targetNamespace = "http://soap.ews.birthcertificate/", className = "birthcertificate.ews.soap.CreateApplicationResponse")
    public SystemMessage createApplication(
        @WebParam(name = "labour", targetNamespace = "")
        Labour labour);

}
