
package webframeapp.servicelogic;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DomainService", targetNamespace = "http://serviceLgoic.webFrameApp/", wsdlLocation = "http://localhost:8080/RDwebFrameApp/DomainService?wsdl")
public class DomainService
    extends Service
{

    private final static URL DOMAINSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webframeapp.servicelogic.DomainService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webframeapp.servicelogic.DomainService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RDwebFrameApp/DomainService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RDwebFrameApp/DomainService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOMAINSERVICE_WSDL_LOCATION = url;
    }

    public DomainService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DomainService() {
        super(DOMAINSERVICE_WSDL_LOCATION, new QName("http://serviceLgoic.webFrameApp/", "DomainService"));
    }

    /**
     * 
     * @return
     *     returns DomainDAO
     */
    @WebEndpoint(name = "SOAPOverHTTP")
    public DomainDAO getSOAPOverHTTP() {
        return super.getPort(new QName("http://serviceLgoic.webFrameApp/", "SOAPOverHTTP"), DomainDAO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DomainDAO
     */
    @WebEndpoint(name = "SOAPOverHTTP")
    public DomainDAO getSOAPOverHTTP(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceLgoic.webFrameApp/", "SOAPOverHTTP"), DomainDAO.class, features);
    }

}
