
package docman.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FileServiceRemote", targetNamespace = "http://services.docman/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileServiceRemote {


    /**
     * 
     * @param requestId
     * @return
     *     returns docman.services.FileRequest
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRequestById", targetNamespace = "http://services.docman/", className = "docman.services.FindRequestById")
    @ResponseWrapper(localName = "findRequestByIdResponse", targetNamespace = "http://services.docman/", className = "docman.services.FindRequestByIdResponse")
    public FileRequest findRequestById(
        @WebParam(name = "requestId", targetNamespace = "")
        int requestId);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param file
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFile", targetNamespace = "http://services.docman/", className = "docman.services.AddFile")
    @ResponseWrapper(localName = "addFileResponse", targetNamespace = "http://services.docman/", className = "docman.services.AddFileResponse")
    public boolean addFile(
        @WebParam(name = "file", targetNamespace = "")
        FileInfo file,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        InputStream arg2);

    /**
     * 
     * @param fileRequest
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeRequest", targetNamespace = "http://services.docman/", className = "docman.services.RemoveRequest")
    @ResponseWrapper(localName = "removeRequestResponse", targetNamespace = "http://services.docman/", className = "docman.services.RemoveRequestResponse")
    public boolean removeRequest(
        @WebParam(name = "fileRequest", targetNamespace = "")
        FileRequest fileRequest);

    /**
     * 
     * @param sharedWith
     * @return
     *     returns java.util.List<docman.services.FileShare>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSahres", targetNamespace = "http://services.docman/", className = "docman.services.GetSahres")
    @ResponseWrapper(localName = "getSahresResponse", targetNamespace = "http://services.docman/", className = "docman.services.GetSahresResponse")
    public List<FileShare> getSahres(
        @WebParam(name = "sharedWith", targetNamespace = "")
        String sharedWith);

    /**
     * 
     * @param fileName
     * @param fileOwner
     * @return
     *     returns docman.services.FileInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByName", targetNamespace = "http://services.docman/", className = "docman.services.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://services.docman/", className = "docman.services.FindByNameResponse")
    public FileInfo findByName(
        @WebParam(name = "fileOwner", targetNamespace = "")
        String fileOwner,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName);

    /**
     * 
     * @param username
     * @return
     *     returns docman.services.FileInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileByUsername", targetNamespace = "http://services.docman/", className = "docman.services.GetFileByUsername")
    @ResponseWrapper(localName = "getFileByUsernameResponse", targetNamespace = "http://services.docman/", className = "docman.services.GetFileByUsernameResponse")
    public FileInfo getFileByUsername(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param fileId
     * @param username
     * @return
     *     returns docman.services.FileInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileById", targetNamespace = "http://services.docman/", className = "docman.services.GetFileById")
    @ResponseWrapper(localName = "getFileByIdResponse", targetNamespace = "http://services.docman/", className = "docman.services.GetFileByIdResponse")
    public FileInfo getFileById(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "fileId", targetNamespace = "")
        int fileId);

    /**
     * 
     * @param requestsFor
     * @return
     *     returns java.util.List<docman.services.FileRequest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequests", targetNamespace = "http://services.docman/", className = "docman.services.GetRequests")
    @ResponseWrapper(localName = "getRequestsResponse", targetNamespace = "http://services.docman/", className = "docman.services.GetRequestsResponse")
    public List<FileRequest> getRequests(
        @WebParam(name = "requestsFor", targetNamespace = "")
        String requestsFor);

    /**
     * 
     * @param fileId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeFile", targetNamespace = "http://services.docman/", className = "docman.services.RemoveFile")
    @ResponseWrapper(localName = "removeFileResponse", targetNamespace = "http://services.docman/", className = "docman.services.RemoveFileResponse")
    public boolean removeFile(
        @WebParam(name = "fileId", targetNamespace = "")
        int fileId);

    /**
     * 
     * @param fileRequest
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveRequest", targetNamespace = "http://services.docman/", className = "docman.services.SaveRequest")
    @ResponseWrapper(localName = "saveRequestResponse", targetNamespace = "http://services.docman/", className = "docman.services.SaveRequestResponse")
    public boolean saveRequest(
        @WebParam(name = "fileRequest", targetNamespace = "")
        FileRequest fileRequest);

    /**
     * 
     * @param fileOwner
     * @return
     *     returns java.util.List<docman.services.FileInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFilesByOwner", targetNamespace = "http://services.docman/", className = "docman.services.GetFilesByOwner")
    @ResponseWrapper(localName = "getFilesByOwnerResponse", targetNamespace = "http://services.docman/", className = "docman.services.GetFilesByOwnerResponse")
    public List<FileInfo> getFilesByOwner(
        @WebParam(name = "fileOwner", targetNamespace = "")
        String fileOwner);

    /**
     * 
     * @param requester
     * @param docOwner
     * @return
     *     returns java.util.List<docman.services.FileInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserDocuments", targetNamespace = "http://services.docman/", className = "docman.services.GetUserDocuments")
    @ResponseWrapper(localName = "getUserDocumentsResponse", targetNamespace = "http://services.docman/", className = "docman.services.GetUserDocumentsResponse")
    public List<FileInfo> getUserDocuments(
        @WebParam(name = "requester", targetNamespace = "")
        String requester,
        @WebParam(name = "docOwner", targetNamespace = "")
        String docOwner);

    /**
     * 
     * @param localDestionation
     * @param remotePath
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://services.docman/", className = "docman.services.DownloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://services.docman/", className = "docman.services.DownloadFileResponse")
    public boolean downloadFile(
        @WebParam(name = "remotePath", targetNamespace = "")
        String remotePath,
        @WebParam(name = "localDestionation", targetNamespace = "")
        String localDestionation);

    /**
     * 
     * @return
     *     returns java.util.List<docman.services.FileInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFiles", targetNamespace = "http://services.docman/", className = "docman.services.GetFiles")
    @ResponseWrapper(localName = "getFilesResponse", targetNamespace = "http://services.docman/", className = "docman.services.GetFilesResponse")
    public List<FileInfo> getFiles();

    /**
     * 
     * @param fileId
     * @param updates
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateFile", targetNamespace = "http://services.docman/", className = "docman.services.UpdateFile")
    @ResponseWrapper(localName = "updateFileResponse", targetNamespace = "http://services.docman/", className = "docman.services.UpdateFileResponse")
    public boolean updateFile(
        @WebParam(name = "fileId", targetNamespace = "")
        int fileId,
        @WebParam(name = "updates", targetNamespace = "")
        FileInfo updates);

    /**
     * 
     * @param shareWith
     * @param fileInfo
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "shareFile", targetNamespace = "http://services.docman/", className = "docman.services.ShareFile")
    @ResponseWrapper(localName = "shareFileResponse", targetNamespace = "http://services.docman/", className = "docman.services.ShareFileResponse")
    public boolean shareFile(
        @WebParam(name = "fileInfo", targetNamespace = "http://services.docman/")
        FileInfo fileInfo,
        @WebParam(name = "shareWith", targetNamespace = "")
        String shareWith);

}
